# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qrscan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qrscan

  target 'qrscan-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'qrscanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'qrscan-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qrscan-tvOS

  target 'qrscan-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end
